### ISSUE TITLE
BFS issue

### ISSUE THREAD

**Issue by muhammad-sayed-mahdy** [OmarBazaraa/Competitive-Programming#3]
https://github.com/OmarBazaraa/Competitive-Programming/blob/1ec226f07fa2d6af922425bddce75b517997626c/graphs/traversal/graph_traversal.cpp#L25
I think it should be
`if(vis[v]++ == 0)` not `if(vis[u]++ == 0)`

**Comment by OmarBazaraa** [comment]
Yup, you're right.
Fixed
Thanks
